spring.application.name=switch-pagos
spring.profiles.default=local

# Servidor
server.port=${SERVER_PORT:8080}

# Base de datos
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/banquito_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:123}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.defer-datasource-initialization=true

# SQL initialization
spring.sql.init.mode=always
spring.sql.init.continue-on-error=true

# Parametros de negocio por entorno
# Hora de corte para ingesta inmediata (0-23)
app.ingest.cutoff-hour=${APP_INGEST_CUTOFF_HOUR:18}
# Ventana para detectar duplicados de archivo en dias
app.validation.duplicate-window-days=${APP_VALIDATION_DUPLICATE_WINDOW_DAYS:30}

# Control de autocreacion de BD (recomendado solo local)
app.db.auto-create=${APP_DB_AUTO_CREATE:false}

# Logging
logging.level.root=${LOGGING_LEVEL_ROOT:INFO}
logging.level.ec.edu.espe.banquito=${LOGGING_LEVEL_EC_EDU_ESPE_BANQUITO:DEBUG}

# Actuator
management.endpoints.web.exposure.include=${MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE:health,info,metrics}
management.endpoint.health.show-details=${MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS:always}
