import { useEffect, useState } from 'react';
import { Banknote, CreditCard, Users } from 'lucide-react';
import Layout from '../../components/layout/Layout';
import { Card, CardHeader } from '../../components/ui/Card';
import Alert from '../../components/ui/Alert';
import StatCard from '../../components/ui/StatCard';
import { AccountsTable, CustomersTable } from '../../components/Tables';
import { coreApi } from '../../api/coreApi';
import { readError, uuid } from '../../utils/format';
import { useAuth } from '../../context/AuthContext';

function Field({label,children}:{label:string;children:any}){return <label className="block"><span className="text-sm font-bold text-slate-700">{label}</span><div className="mt-2">{children}</div></label>}
const input='w-full rounded-2xl border border-slate-200 px-4 py-3 outline-none focus:border-[#123B66] focus:ring-4 focus:ring-blue-100';

export default function StaffPage({activeSection='clientes',onNavigate}:{activeSection?:string;onNavigate?:(key:string)=>void}){
 const {session}=useAuth(); const isAdvisor=session?.role==='ASESOR';
 const [customers,setCustomers]=useState<any[]>([]); const [accounts,setAccounts]=useState<any[]>([]); const [msg,setMsg]=useState(''); const [err,setErr]=useState('');
 const [customer,setCustomer]=useState<any>({customerType:activeSection==='empresa'?'JURIDICO':'NATURAL',identificationType:'CEDULA',identification:'',firstName:'',lastName:'',birthDate:'',legalName:'',constitutionDate:'',email:'',mobilePhone:'',address:'',status:'ACTIVO'});
 const [account,setAccount]=useState<any>({accountNumber:'',customerId:1,balance:0,status:'ACTIVA',branch:{id:1},accountSubtype:{id:1}});
 const [tx,setTx]=useState<any>({accountNumber:'',amount:0,description:'Depósito ventanilla'});
 const load=async()=>{try{const [c,a]=await Promise.all([coreApi.customers(),coreApi.accounts()]); setCustomers(c); setAccounts(a)}catch(e){setErr(readError(e))}}; useEffect(()=>{load()},[]);
 useEffect(()=>{if(activeSection==='natural')setCustomer((c:any)=>({...c,customerType:'NATURAL'})); if(activeSection==='empresa')setCustomer((c:any)=>({...c,customerType:'JURIDICO'}));},[activeSection]);
 async function saveCustomer(){setErr('');setMsg('');try{await coreApi.createCustomer(customer); setMsg('Cliente enviado correctamente al Core.'); await load()}catch(e){setErr(readError(e))}}
 async function saveAccount(){setErr('');setMsg('');try{await coreApi.createAccount(account); setMsg('Cuenta enviada correctamente al Core.'); await load()}catch(e){setErr(readError(e))}}
 async function sendTx(type:'credit'|'debit'){setErr('');setMsg('');try{const payload={...tx,transactionUuid:uuid(),amount:Number(tx.amount)}; await (type==='credit'?coreApi.credit(payload):coreApi.debit(payload)); setMsg(type==='credit'?'Depósito enviado al Core.':'Retiro enviado al Core.'); await load()}catch(e){setErr(readError(e))}}
 return <Layout activeKey={activeSection} onNavigate={onNavigate}>
  <div className="mb-6"><h2 className="text-2xl font-extrabold text-slate-950">{isAdvisor?'Portal Asesor':'Portal Cajero'}</h2><p className="text-sm text-slate-500">Operación interna del banco: clientes, cuentas, depósitos y retiros.</p></div>
  {msg&&<div className="mb-5"><Alert type="success">{msg}</Alert></div>}{err&&<div className="mb-5"><Alert type="error">{err}</Alert></div>}
  <div className="grid gap-4 md:grid-cols-3"><StatCard title="Clientes" value={String(customers.length)} detail="Naturales/Jurídicos" icon={Users}/><StatCard title="Cuentas" value={String(accounts.length)} detail="Productos abiertos" icon={CreditCard}/><StatCard title="Operación" value={isAdvisor?'Asesoría':'Caja'} detail="Rol activo" icon={Banknote}/></div>
  {isAdvisor && (activeSection==='clientes')&&<div className="mt-6"><Card><CardHeader title="Clientes registrados" subtitle="Consulta funcional hacia Core"/><div className="p-5"><CustomersTable customers={customers}/></div></Card></div>}
  {isAdvisor && (activeSection==='natural'||activeSection==='empresa')&&<div className="mt-6 max-w-5xl"><Card><CardHeader title={activeSection==='natural'?'Crear persona natural':'Crear empresa'} subtitle="Formulario separado por tipo de titular"/><div className="grid gap-4 p-5 md:grid-cols-2"><Field label="Tipo"><input disabled className={input} value={customer.customerType}/></Field><Field label="Identificación"><input className={input} value={customer.identification} onChange={e=>setCustomer({...customer,identification:e.target.value})}/></Field>{customer.customerType==='NATURAL'?<><Field label="Nombres"><input className={input} value={customer.firstName} onChange={e=>setCustomer({...customer,firstName:e.target.value})}/></Field><Field label="Apellidos"><input className={input} value={customer.lastName} onChange={e=>setCustomer({...customer,lastName:e.target.value})}/></Field><Field label="Fecha nacimiento"><input type="date" className={input} value={customer.birthDate} onChange={e=>setCustomer({...customer,birthDate:e.target.value})}/></Field></>:<><Field label="Razón social"><input className={input} value={customer.legalName} onChange={e=>setCustomer({...customer,legalName:e.target.value})}/></Field><Field label="Constitución"><input type="date" className={input} value={customer.constitutionDate} onChange={e=>setCustomer({...customer,constitutionDate:e.target.value})}/></Field></>}<Field label="Correo"><input className={input} value={customer.email} onChange={e=>setCustomer({...customer,email:e.target.value})}/></Field><Field label="Teléfono"><input className={input} value={customer.mobilePhone} onChange={e=>setCustomer({...customer,mobilePhone:e.target.value})}/></Field><Field label="Dirección"><input className={input} value={customer.address} onChange={e=>setCustomer({...customer,address:e.target.value})}/></Field><button onClick={saveCustomer} className="self-end rounded-2xl bg-[#0B1F3A] px-5 py-3 font-bold text-white">Guardar cliente</button></div></Card></div>}
  {isAdvisor && activeSection==='cuentas'&&<div className="mt-6 grid gap-6 xl:grid-cols-2"><Card><CardHeader title="Abrir cuenta" subtitle="Vinculada a cliente y sucursal"/><div className="grid gap-4 p-5 md:grid-cols-2"><Field label="Número de cuenta"><input className={input} value={account.accountNumber} onChange={e=>setAccount({...account,accountNumber:e.target.value})}/></Field><Field label="ID cliente"><input type="number" className={input} value={account.customerId} onChange={e=>setAccount({...account,customerId:Number(e.target.value)})}/></Field><Field label="Saldo inicial"><input type="number" className={input} value={account.balance} onChange={e=>setAccount({...account,balance:Number(e.target.value)})}/></Field><Field label="Estado"><select className={input} value={account.status} onChange={e=>setAccount({...account,status:e.target.value})}><option>ACTIVA</option><option>INACTIVA</option><option>BLOQUEADA</option><option>SUSPENDIDA</option></select></Field><button onClick={saveAccount} className="self-end rounded-2xl bg-[#0B1F3A] px-5 py-3 font-bold text-white">Abrir cuenta</button></div></Card><Card><CardHeader title="Cuentas existentes" subtitle="Productos abiertos"/><div className="p-5"><AccountsTable accounts={accounts}/></div></Card></div>}
  {!isAdvisor && activeSection==='buscar'&&<div className="mt-6"><Card><CardHeader title="Buscar cuenta" subtitle="Consulta de productos para caja"/><div className="p-5"><AccountsTable accounts={accounts}/></div></Card></div>}
  {!isAdvisor && (activeSection==='deposito'||activeSection==='retiro')&&<div className="mt-6 max-w-3xl"><Card><CardHeader title={activeSection==='deposito'?'Depósito por ventanilla':'Retiro por ventanilla'} subtitle="Operación enviada al motor transaccional"/><div className="grid gap-4 p-5"><Field label="Cuenta"><input className={input} value={tx.accountNumber} onChange={e=>setTx({...tx,accountNumber:e.target.value})}/></Field><Field label="Monto"><input type="number" className={input} value={tx.amount} onChange={e=>setTx({...tx,amount:Number(e.target.value)})}/></Field><Field label="Descripción"><input className={input} value={tx.description} onChange={e=>setTx({...tx,description:e.target.value})}/></Field><button onClick={()=>sendTx(activeSection==='deposito'?'credit':'debit')} className={`rounded-2xl px-5 py-3 font-bold text-white ${activeSection==='deposito'?'bg-emerald-600':'bg-red-600'}`}>{activeSection==='deposito'?'Depositar':'Retirar'}</button></div></Card></div>}
  {!isAdvisor && activeSection==='mov'&&<div className="mt-6"><Card><CardHeader title="Movimientos" subtitle="Historial de cuentas"/><div className="p-5"><AccountsTable accounts={accounts}/></div></Card></div>}
 </Layout>
}
